title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
logo: assets/images/IMG_3948.jpg
show_downloads:True
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
